runmode: debug
addr: :80
name: kbs
url: http://127.0.0.1:80
max_ping_count: 10

log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/kbs.log
  log_format_text: false
  rollingPolicy: size   # 日志转存策略,选 daily 则根据天进行转存，如果是 size 则根据大小进行转存
  log_rotate_date: 1    # 转存时间为1天
  log_rotate_size: 1024 # 转存大小为1MB
  log_backup_count: 7   # 备份文件的最大个数
db:
  name: kbs_admin
  addr: 127.0.0.1:3306
  username: root
  password: root